// Generates an IPA dictionary for the FIXED vocabulary used in shadowing /
// read-aloud / practice content, using CMUdict. Runs at build time only — the
// output JSON contains only the few hundred words actually used, so the runtime
// bundle stays small. Run: `node scripts/gen-ipa.mjs`.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const _cmu = require("cmu-pronouncing-dictionary");
const _root = _cmu.default ?? _cmu;
const cmudict = _root.dictionary ?? _root;

const FILES = [
  "src/lib/shadowing-data.ts",
  "src/lib/toeic-data.ts",
  "src/lib/pronunciation.ts",
  "src/lib/samples.ts",
];

// ARPAbet → IPA.
const M = {
  AA: "ɑː", AE: "æ", AH: "ʌ", AO: "ɔː", AW: "aʊ", AY: "aɪ", B: "b", CH: "tʃ",
  D: "d", DH: "ð", EH: "ɛ", ER: "ɜːr", EY: "eɪ", F: "f", G: "ɡ", HH: "h",
  IH: "ɪ", IY: "iː", JH: "dʒ", K: "k", L: "l", M: "m", N: "n", NG: "ŋ",
  OW: "oʊ", OY: "ɔɪ", P: "p", R: "r", S: "s", SH: "ʃ", T: "t", TH: "θ",
  UH: "ʊ", UW: "uː", V: "v", W: "w", Y: "j", Z: "z", ZH: "ʒ",
};

function arpaToken(t) {
  const stress = (t.match(/(\d)$/) || [])[1];
  const base = t.replace(/\d/g, "");
  if (base === "AH" && stress === "0") return "ə";
  if (base === "ER" && stress === "0") return "ər";
  return M[base] ?? "";
}

function toIPA(arpa) {
  const clean = arpa.split("#")[0].trim(); // drop trailing "# comment"
  return "/" + clean.split(/\s+/).map(arpaToken).join("") + "/";
}

// Collect words from quoted string literals only (avoids code identifiers).
const words = new Set();
for (const file of FILES) {
  let text;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    continue;
  }
  const strings = text.match(/"[^"]*"|'[^']*'/g) || [];
  for (const s of strings) {
    const inner = s.slice(1, -1);
    for (const w of inner.toLowerCase().match(/[a-z']+/g) || []) {
      words.add(w.replace(/^'+|'+$/g, ""));
    }
  }
}

const dict = {};
let hit = 0;
for (const w of [...words].sort()) {
  const arpa = cmudict[w];
  if (arpa) {
    dict[w] = toIPA(arpa);
    hit++;
  }
}

const out = `// AUTO-GENERATED by scripts/gen-ipa.mjs — do not edit by hand.
// IPA for the fixed practice vocabulary (CMUdict → IPA).
export const IPA_DICT: Record<string, string> = ${JSON.stringify(dict, null, 0)};
`;
writeFileSync("src/lib/ipa-dict.generated.ts", out);
console.log(`IPA dict generated: ${hit}/${words.size} words → src/lib/ipa-dict.generated.ts`);
